### PR TITLE
jQuery call on default.hbs

### PR DESCRIPTION
**Pull request by camilodelvasto**
On a clean local install there was a js error... jQuery was not being loaded. So I added the call on default.hbs.

### CODE REVIEW

**Comment by camilodelvasto** [comment]
Hi there, fyi is because ghost is not including jQuery automatically anymore, so the line had to be added on Casper as well. Anybody maintaining this repository? Can I help?

**Comment by kc9zyz** [comment]
@grmmph Please accept this pull request, the theme no longer works out of the box with Ghost.

**Comment by tasmo** [comment]
+1

**Comment by grmmph** [comment]
Wow, this repo is really not maintained.
I should soon go over all the the issues/PR and clean up some code.

Sorry everyone for late respond and the bad maintenance. Have a good Friday :beers:

**Comment by zebheone** [comment]
you have a good friday too!

Inviato da Outlook Mobile

On Fri, Feb 5, 2016 at 2:06 AM -0800, "Yonatan Wolowelsky" notifications@github.com wrote:

Wow, this repo is really not maintained.
I should soon go over all the the issues/PR and clean up some code.

Sorry everyone for late respond and the bad maintenance. Have a good Friday :beers:

---

**Pull request merged**
